services:
  # PostgreSQL Database Service
  db:
    image: postgres:18
    container_name: firmness_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwe.123*
      POSTGRES_DB: firmness
    ports:
      - "5433:5432"
    volumes:
      - firmness_postgres_data:/var/lib/postgresql
    restart: unless-stopped

  # ASP.NET Core Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firmness_web
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Default: "Host=db;Port=5432;Database=firmness;Username=postgres;Password=Qwe.123*"
    depends_on:
      - db
    restart: on-failure

volumes:
  firmness_postgres_data:
    driver: local
